// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Cellenzapp.Native.iOS
{
	public partial class CellExpertsDetailViewController : UIViewController
	{
		public CellExpertsDetailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
